name: 'coverage'
on:
    pull_request:
        branches:
            - main
            - dev
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: borales/actions-yarn@v2.3.0
              with:
                  cmd: install # will run `yarn install` command
            - uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 5 # optional parameter
                  package-manager: yarn
                  skip-step: install # this is due to a bug in the action itself, trying to manually install it.

