import { Network, SupportedNetworks } from "./types";
import {
  arbitrum,
  polygon,
  mainnet,
  avalanche,
  moonriver,
  fantom,
} from "assets/networks";

export const NETWORKS: {
  [networkId in SupportedNetworks]: Network;
} = {
  1: {
    name: "Mainnet",
    rpcUrl: process.env.RPC_URL_1!,
    infoPageUrl: "https://etherscan.io/tx/",
    infoPage: "Etherscan",
    logo: mainnet,
    backgroundColor: "#364683",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "",
    imageURL: "/networks/mainnet.svg",
    chainId: 1,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "ETH",
      decimals: 18,
      imageURL: "/networks/mainnet.svg",
      id: "eth",
      provider: "native",
      crossChainId: "-1",
    },
  },
  42161: {
    name: "Arbitrum",
    rpcUrl: process.env.RPC_URL_42161!,
    infoPageUrl: "https://arbiscan.io/tx/",
    infoPage: "Arbiscan",
    logo: arbitrum,
    backgroundColor: "#23A9C7",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "https://arb1.arbitrum.io/rpc",
    imageURL: "/networks/arbitrum.svg",
    chainId: 42161,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "ETH",
      decimals: 18,
      imageURL: "/networks/arbitrum.svg",
      id: "eth",
      provider: "native",
      crossChainId: "-1",
    },
  },
  137: {
    name: "Polygon",
    rpcUrl: process.env.RPC_URL_137!,
    infoPageUrl: "https://polygonscan.com/tx/",
    infoPage: "Polygonscan",
    logo: polygon,
    backgroundColor: "#8D49FF",
    defaultTokenSymbol: "MATIC",
    publicRpcUrl: "https://rpc-mainnet.maticvigil.com/",
    imageURL: "/networks/matic.svg",
    chainId: 137,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "MATIC",
      decimals: 18,
      imageURL: "/networks/matic.svg",
      id: "matic",
      provider: "native",
      crossChainId: "-1",
    },
  },
  43114: {
    name: "Avalanche",
    rpcUrl: process.env.RPC_URL_43114!,
    infoPageUrl: "https://cchain.explorer.avax.network/tx/",
    infoPage: "Avax Scan",
    logo: avalanche,
    backgroundColor: "#C73738",
    defaultTokenSymbol: "AVAX",
    publicRpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    imageURL: "/networks/avalanche.svg",
    chainId: 43114,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "AVAX",
      decimals: 18,
      imageURL: "/networks/avalanche.svg",
      id: "avax",
      provider: "native",
      crossChainId: "-1",
    },
  },
  3: {
    name: "Ropsten",
    rpcUrl: process.env.RPC_URL_3!,
    infoPageUrl: "https://ropsten.etherscan.io/tx/",
    infoPage: "Etherscan",
    logo: mainnet,
    backgroundColor: "#364683",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "",
    imageURL: "/networks/mainnet.svg",
    chainId: 3,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "ETH",
      decimals: 18,
      imageURL: "/networks/mainnet.svg",
      id: "eth",
      provider: "native",
      crossChainId: "-1",
    },
  },
  80001: {
    name: "Mumbai",
    rpcUrl: process.env.RPC_URL_80001!,
    infoPageUrl: "https://mumbai.polygonscan.com/tx/",
    infoPage: "Polygonscan",
    logo: polygon,
    backgroundColor: "#8D49FF",
    defaultTokenSymbol: "MATIC",
    publicRpcUrl: "https://rpc-mumbai.maticvigil.com/",
    imageURL: "/networks/matic.svg",
    chainId: 80001,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "MATIC",
      decimals: 18,
      imageURL: "/networks/matic.svg",
      id: "matic",
      provider: "native",
      crossChainId: "-1",
    },
  },
  421611: {
    name: "Rinkeby",
    rpcUrl: process.env.RPC_URL_421611!,
    infoPageUrl: "https://rinkeby-explorer.arbitrum.io/tx/",
    infoPage: "Arbitrum.io",
    logo: arbitrum,
    backgroundColor: "#23A9C7",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "https://rinkeby.arbitrum.io/rpc",
    imageURL: "/networks/mainnet.svg",
    chainId: 421611,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "ETH",
      decimals: 18,
      imageURL: "/networks/mainnet.svg",
      id: "eth",
      provider: "native",
      crossChainId: "-1",
    },
  },
  1285: {
    name: "Moonriver",
    rpcUrl: process.env.RPC_URL_1285!,
    infoPageUrl: "https://blockscout.moonriver.moonbeam.network/tx/",
    infoPage: "Moonriver Blockscout",
    logo: moonriver,
    backgroundColor: "#F3B406",
    defaultTokenSymbol: "MOVR",
    publicRpcUrl: "https://rpc.moonriver.moonbeam.network",
    imageURL: "/networks/moonriver.svg",
    chainId: 1285,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "MOVR",
      decimals: 18,
      imageURL: "/networks/moonriver.svg",
      id: "movr",
      provider: "native",
      crossChainId: "-1",
    },
  },
  250: {
    name: "Fantom",
    rpcUrl: process.env.RPC_URL_250!,
    infoPageUrl: "https://ftmscan.com/tx/",
    infoPage: "Fantom Scan",
    logo: fantom,
    backgroundColor: "#4172CC",
    defaultTokenSymbol: "FTM",
    publicRpcUrl: "https://rpc.ftm.tools",
    imageURL: "/networks/fantom.svg",
    chainId: 250,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "FTM",
      decimals: 18,
      imageURL: "/networks/fantom.svg",
      id: "ftm",
      provider: "native",
      crossChainId: "-1",
    },
  },
  42: {
    name: "Kovan",
    rpcUrl: process.env.RPC_URL_42!,
    infoPageUrl: "https://kovan-explorer.etherium.io/tx/",
    infoPage: "kovan.io",
    logo: arbitrum,
    backgroundColor: "#23A9C7",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "https://kovan.etherium.io/rpc",
    imageURL: "/networks/mainnet.svg",
    chainId: 42,
    nativeToken: {
      amms: [],
      icon: "",
      address: "0x0000000000000000000000000000000000000000",
      symbol: "ETH",
      decimals: 18,
      imageURL: "/networks/mainnet.svg",
      id: "eth",
      provider: "native",
      crossChainId: "-1",
    },
  },
};
