import { DEFI_CONFIG } from "./config";
import { Token, TokenId } from "./types";

export const TOKEN_IDS = DEFI_CONFIG.tokenIds;
export const TOKENS: { [key in TokenId]: Token } = {
  eth: {
    id: "eth",
    icon: "/tokens/eth-mainnet.svg",
    symbol: "ETH",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee1",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/eth-mainnet.svg",
    provider: "native",
    amms: [],
  },
  matic: {
    id: "matic",
    icon: "/tokens/polygon-matic.svg",
    symbol: "MATIC",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee2",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/polygon-matic.svg",
    provider: "native",
    amms: [],
  },
  avax: {
    id: "avax",
    icon: "/tokens/avalanche.svg",
    symbol: "AVAX",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee3",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/avalanche.svg",
    provider: "native",
    amms: [],
  },
  weth: {
    id: "weth",
    icon: "/tokens/weth-mainnet.svg",
    symbol: "wETH",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee4",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/weth-mainnet.svg",
    provider: "native",
    amms: [],
  },
  usdc: {
    id: "usdc",
    icon: "/tokens/usd-coin-usdc.svg",
    symbol: "USDC",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee5",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/usd-coin-usdc.svg",
    provider: "native",
    amms: [],
  },
  dot: {
    id: "dot",
    icon: "/tokens/polkadot.svg",
    symbol: "DOT",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee6",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/polkadot.svg",
    provider: "native",
    amms: [],
  },
  uni: {
    id: "uni",
    icon: "/tokens/uniswap.svg",
    symbol: "UNI",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee7",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/uniswap.svg",
    provider: "native",
    amms: [],
  },
  ftm: {
    id: "ftm",
    icon: "/tokens/fantom.svg",
    symbol: "FTM",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee8",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/fantom.svg",
    provider: "native",
    amms: [],
  },
  pica: {
    id: "pica",
    icon: "/tokens/picasso.svg",
    symbol: "PICA",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee9",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/picasso.svg",
    provider: "native",
    amms: [],
  },
  movr: {
    id: "movr",
    icon: "/tokens/movr.svg",
    symbol: "MOVR",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/movr.svg",
    provider: "native",
    amms: [],
  },
  ksm: {
    id: "ksm",
    icon: "/tokens/dotsama-kusama.svg",
    symbol: "KSM",
    address: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    decimals: 18,
    crossChainId: "-1",
    imageURL: "/tokens/dotsama-kusama.svg",
    provider: "native",
    amms: [],
  },
};
export const getToken = (tokenId: TokenId): Token => TOKENS[tokenId];
